#' General Eduation Category lookup table
pre_professional_track_alias_lookup <- tibble::tribble(
  ~alias, ~program,
  "pre pt", "PT.PRE2",
  "physical therapy", "PT.PRE2",
  "pre physical therapy", "PT.PRE2",
  "pre physical therapy track", "PT.PRE2",
  "pre med", "MD.PRE2",
  "pre medicine", "MD.PRE2",
  "pre medicine track", "MD.PRE2",
  "pre vet", "VET.PRE2",
  "pre veterinary science", "VET.PRE2",
  "pre veterinary science track", "VET.PRE2",
  "pre genetic counseling", "GC.PRE2",
  "pre genetic counseling track", "GC.PRE2",
  "pre pa", "PA.PRE2",
  "pre physicians assistant", "PA.PRE2",
  "pre physicians assistnt track", "PA.PRE2",
  "pre dentistry", "DENT.PRE2",
  "pre dentistry track", "DENT.PRE2",
  "pre clinical exercise physiology track", "CEP.PRE2",
  "pre clinical exerc phys track", "CEP.PRE2",
  "pre clinical exercise physiology", "CEP.PRE2",
  "pre chiropractic", "CHIRO.PRE2",
  "pre chiropractic track", "CHIRO.PRE2",
  "pre engineering", "ENGR.PRE2",
  "pre engineering track", "ENGR.PRE2",
  "pre forestry", "FOREST.PRE2",
  "pre forestry track", "FOREST.PRE2",
  "pre health", "HLTH.PRE2",
  "pre health track", "HLTH.PRE2",
  "pre law", "LAW.PRE2",
  "pre law track", "LAW.PRE2",
  "pre optometry", "OPT.PRE2",
  "pre optometry track", "OPT.PRE2",
  "pre occupational therapy", "OT.PRE2",
  "pre occupational therapy track", "OT.PRE2",
  "pre ot", "TO.PRE2",
  "pre peace corps", "PEACE.PRE2",
  "pre peace corps track", "PEACE.PRE2",
  "pre pharmacy", "PHARM.PRE2",
  "pre pharmacy track", "PHARM.PRE2"
)

#' General Education Category lookup table
general_education_category_lookup <- tibble::tribble(
  ~gen.ed.or.writing.emphasis, ~gen.ed.category.name,
  "C1Q", "Quantitative Reasoning",
  "C2S", "Spoken Literacy",
  "C2T", "The Stories We Tell",
  "C2W", "Written Literacy",
  "C3B", "Social & Behavioral Studies",
  "C3F", "Social Foundations for Success",
  "C4A", "Arts & Aesthetics",
  "C4H", "The Pasts that Define Us",
  "C5M", "Mind, Body, & Planet",
  "C5XE", "Experiential Science",
  "C6U", "The Communities of the U.S.",
  "C6W", "The Cultures of Our World",
)

#' Discipline lookup table
lookup_discipline_lookup <- tibble::tribble(
  ~dept, ~discpln,
  "ACC", "Business",
  "ANT", "Social Sciences",
  "ART", "Arts",
  "BIO", "Natural Sciences",
  "CHM", "Natural Sciences",
  "CS", "Mathematical & Computational Sciences",
  "CST", "Social Sciences",
  "DES", "Education",
  "ECO", "Business",
  "ENG", "Humanities",
  "ESS", "Human Performance & Applied Health",
  "FIN", "Business",
  "GCL", "Humanities",
  "GEO", "Environmental Science",
  "HIS", "Humanities",
  "HP", "Health Sciences",
  "IS", "Business",
  "MGT", "Business",
  "MIC", "Natural Sciences",
  "MKT", "Business",
  "MTH", "Mathematical & Computational Sciences",
  "MUS", "Arts",
  "PH", "Health Sciences",
  "PHL", "Humanities",
  "PHY", "Natural Sciences",
  "POL", "Social Sciences",
  "PROV", "University",
  "PSY", "Social Sciences",
  "RGS", "Social Sciences",
  "RMRT", "Human Performance & Applied Health",
  "SOC", "Social Sciences",
  "THA", "Arts",
)

#' Subject lookup table
lookup_subject_lookup <- tibble::tribble(
  ~subject, ~dept,
  "ACC", "ACC",
  "ANT", "ANT",
  "ARC", "ANT",
  "ART", "ART",
  "ATS", "ESS",
  "BIO", "BIO",
  "BLAW", "ACC",
  "CHE", "PH",
  "CHI", "GCL",
  "CHM", "CHM",
  "CLI", "MIC",
  "CPE", "CS",
  "CRIM", "SOC",
  "CS", "CS",
  "CST", "CST",
  "CT", "CS",
  "CYB", "CST",
  "CYC", "PSY",
  "DMK", "MKT",
  "DMS", "HP",
  "DOS", "HP",
  "DS", "MTH",
  "DSC", "MTH",
  "ECE", "DES",
  "ECO", "ECO",
  "EDS", "DES",
  "EDU", "DES",
  "EFN", "DES",
  "ENG", "ENG",
  "ENV", "PHL",
  "ESS", "ESS",
  "FIN", "FIN",
  "FNS", "BIO",
  "FNT", "CS",
  "FRE", "GCL",
  "FYS", "PROV",
  "GCL", "GCL",
  "GEO", "GEO",
  "GER", "GCL",
  "HCA", "PH",
  "HCK", "GCL",
  "HIS", "HIS",
  "HMG", "GCL",
  "HP", "HP",
  "HPR", "ESS",
  "INS", "HIS",
  "IS", "IS",
  "ITM", "IS",
  "JPN", "GCL",
  "LS", "PROV",
  "MGT", "MGT",
  "MIC", "MIC",
  "MIND", "RMRT",
  "MKT", "MKT",
  "MS", "MS",
  "MTH", "MTH",
  "MUA", "MUS",
  "MUS", "MUS",
  "NEU", "PSY",
  "NMT", "HP",
  "NUT", "BIO",
  "OT", "HP",
  "PAS", "HP",
  "PH", "PH",
  "PHL", "PHL",
  "PHY", "PHY",
  "POL", "POL",
  "PSY", "PSY",
  "PTS", "HP",
  "PUB", "POL",
  "RAD", "HP",
  "RDG", "DES",
  "REC", "RMRT",
  "RGS", "RGS",
  "RT", "HP",
  "RTH", "RMRT",
  "RUS", "GCL",
  "SAA", "SAA",
  "SOC", "SOC",
  "SPA", "GCL",
  "SPE", "DES",
  "SPY", "PSY",
  "STAT", "MTH",
  "THA", "THA",
  "TSL", "DES",
  "UWL", "PROV",
)
